name: Build and Deploy (main)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Create dot env file
        run: |
          touch .env
          echo "AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}" >> .env
          echo "AUTH_CLIENT_ID=${{ secrets.AUTH_CLIENT_ID }}" >> .env
          echo "AUTH_CLIENT_SERCRET=${{ secrets.AUTH_CLIENT_SERCRET }}" >> .env
          echo "AUTH_AUDIENCE=${{ secrets.AUTH_AUDIENCE }}" >> .env
          echo "COFFEE_NOTE_API=${{ secrets.COFFEE_NOTE_API }}" >> .env
          echo "MS_CLARITY_ID=${{ secrets.MS_CLARITY_ID }}" >> .env
      - name: Install dependencies
        run: npm install -g netlify-cli --unsafe-perm=true
      - name: Install project dependencies
        run: yarn
      - name: Generate build
        run: env && yarn generate
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth $NETLIFY_AUTH_TOKEN --dir dist --prod
        

